--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KygekTeam/KygekWhitelistKick
build-by-default: true
branches:
- master
projects:
  KygekWhitelistKick:
    path: ""
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3
    - src: JackMD/UpdateNotifier/UpdateNotifier
      version: ^2.1
...
