---
#     _    __                  _                                     _
#    | |  / /                 | |                                   | |
#    | | / /                  | |                                   | |
#    | |/ / _   _  ____   ____| | ______ ____   _____ ______   ____ | | __
#    | |\ \| | | |/ __ \ / __ \ |/ /  __/ __ \ / __  | _  _ \ / __ \| |/ /
#    | | \ \ \_| | <__> |  ___/   <| / | <__> | <__| | |\ |\ | <__> |   <
# By |_|  \_\__  |\___  |\____|_|\_\_|  \____^_\___  |_||_||_|\____^_\|\_\
#              | |    | |                          | |
#           ___/ | ___/ |                          | |
#          |____/ |____/                           |_|
#
# Kicks not whitelisted players when server whitelist is enabled
# Copyright (C) 2020-2023 Kygekraqmak, KygekTeam
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# he Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#

name: KygekWhitelistKick
version: 2.2.0
main: Kygekraqmak\KygekWhitelistKick\WhitelistKick
api: 5.0.0
authors: [Kygekraqmak, KygekTeam, thebigcrafter]
description: Kicks not whitelisted players when server whitelist is enabled
website: https://github.com/KygekTeam/KygekWhitelistKick

permissions:
  kygekwhitelistkick.cmd:
    description: Permission to use all KygekWhitelistKick commands
    default: op
  kygekwhitelistkick.cmd.help:
    description: Permission to see KygekWhitelistKick commands
    default: op
  kygekwhitelistkick.cmd.off:
    description: Permission to turn off KygekWhitelistKick
    default: op
  kygekwhitelistkick.cmd.on:
    description: Permission to turn on KygekWhitelistKick
    default: op
  kygekwhitelistkick.cmd.set:
    description: Permission to change kick reason
    default: op
...
